# Map file paths during tests to the canonical path in the repo
fixes:
    # Removes the prefix we use during github actions, use glob to support forks
    - "src/github.com/*/coredhcp/::"
    - "github.com/*/coredhcp/::"
