language: go

os: linux
dist: bionic

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - master

env:
  global:
    - GO111MODULE=on
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=linters

before_install:
  - go get -t -v ./...
  - go get -t -v github.com/stretchr/testify/...

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script: |
  set -x
  case $TEST_SUITE in
  unit)
      ./.travis/setup-integ.sh
      ./.travis/tests.sh
      ;;
  linters)
      ./.travis/linters.sh
      ;;
  *)
      echo "[!] Unknown test suite: ${TEST_SUITE}. Exiting."
      exit 1
  esac

after_success:
  - bash <(curl -s https://codecov.io/bash)


jobs:
  include:
    - name: Generator/main entrypoint drift
      script: ./.travis/check-generator-main.sh
