name: Lint

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # version: v3.0.0

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go
          # skip-go-installation: true
  checklicenses:
    name: checklicenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check license headers
        run: |
          set -exu
          go get github.com/u-root/u-root/tools/checklicenses
          go install github.com/u-root/u-root/tools/checklicenses
          $(go env GOPATH)/bin/checklicenses -c .ci/checklicenses_config.json
